name: "Clean the GenBank metadata"

# This will run once a day at 6am, on PRs, and on pushes to master
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  find_hosts:
    name: "Find hosts in GBIF"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Julia 1.4.0 
        uses: julia-actions/setup-julia@latest
        with:
          version: 1.4.0
      - name: Build dependencies 
        uses: julia-actions/julia-buildpkg@latest
        env:
          PYTHON: ""
      - name: Get names from GBIF
        run: julia --project scripts/datacleaning/01_extract_hosts.jl
        env:
          PYTHON: ""
      - name: Upload usable data folder
        uses: actions/upload-artifact@v1
        with:
          name: hostnames_csv_files
          path: data/hostnames/
  get_occurrences:
    name: Get occurrences for known hosts
    needs: find_hosts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve the CSV files with host taxonomy
        uses: actions/download-artifact@v1
        with:
          name: hostnames_csv_files
          path: data/hostnames/
      - name: Setup Julia 1.4.0 
        uses: julia-actions/setup-julia@latest
        with:
          version: 1.4.0
      - name: Build dependencies 
        uses: julia-actions/julia-buildpkg@latest
        env:
          PYTHON: ""
      - name: Get occurrences from GBIF
        run: julia --project scripts/occurrences/01_occurrences.jl
        env:
          PYTHON: ""
      - name: Upload usable data folder
        uses: actions/upload-artifact@v1
        with:
          name: occurrences_csv_files
          path: data/occurrences/
  get_interactions:
      name: Get interactions for known hosts and cleaned viruses
      needs: find_hosts
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Retrieve the CSV files with host taxonomy
          uses: actions/download-artifact@v1
          with:
            name: hostnames_csv_files
            path: data/hostnames/
        - name: Setup Julia 1.4.0 
          uses: julia-actions/setup-julia@latest
          with:
            version: 1.4.0
        - name: Build dependencies 
          uses: julia-actions/julia-buildpkg@latest
          env:
            PYTHON: ""
        - name: Aggregate interaction data
          run: julia --project scripts/network/01_generate_network_files.jl
          env:
            PYTHON: ""
        - name: Upload usable data folder
          uses: actions/upload-artifact@v1
          with:
            name: interactions_csv_file
            path: data/network/
  likely_hosts_through_linfilt:
      name: Predict likely hosts through linear filtering
      needs: get_interactions
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Retrieve the CSV files with interactions
          uses: actions/download-artifact@v1
          with:
            name: interactions_csv_file
            path: data/network/
        - name: Setup Julia 1.4.0 
          uses: julia-actions/setup-julia@latest
          with:
            version: 1.4.0
        - name: Build dependencies 
          uses: julia-actions/julia-buildpkg@latest
          env:
            PYTHON: ""
        - name: Run the linear filter
          run: julia --project scripts/analysis/02_linear_filter_interactions.jl
          env:
            PYTHON: ""
        - name: Upload usable data folder
          uses: actions/upload-artifact@v1
          with:
            name: RESULT_likely_hosts_linear_filtering
            path: results/link_prediction/
